package:
  name: change_fasta_deflines
  version: 0.0.1

source:
  git_url: https://github.com/DiDigsDNA/change_fasta_deflines
  git_rev: master

requirements:
  run:
    - python 2.7

build:
  number: 0

about:
  home: https://github.com/DiDigsDNA/change_fasta_deflines
